"""What the acceptance grader refuses to accept.

The grader's happy path is trivial — it emits a report either way. What is worth
testing is the set of things it must not do: pass a project with a fabricated
claim, pass a figure that argues for nothing, pass a dimension it could not see,
and put a score on offline-stub output at all.

Every fixture here is built in tmp_path from literals rather than by running the
pipeline, because a fixture produced by the system under test cannot demonstrate
that the grader would have caught the system being wrong.
"""
import importlib.util
import json
import shutil
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
GRADE_PY = REPO / "acceptance" / "grade.py"

# The grader is an operator script, not a package: it must run against a project
# directory on a machine where `researchforge` may not be installed at all. So it
# is loaded by path here rather than imported, and registered in sys.modules
# before execution because @dataclass resolves annotations through it.
_spec = importlib.util.spec_from_file_location("rf_acceptance_grade", GRADE_PY)
grade_mod = importlib.util.module_from_spec(_spec)
sys.modules["rf_acceptance_grade"] = grade_mod
_spec.loader.exec_module(grade_mod)


# --------------------------------------------------------------------------
# fixture builder
# --------------------------------------------------------------------------
def _w(root: Path, rel: str, payload) -> Path:
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(payload, str):
        p.write_text(payload, encoding="utf-8")
    elif rel.endswith(".jsonl"):
        p.write_text("".join(json.dumps(r, sort_keys=True) + "\n" for r in payload),
                     encoding="utf-8")
    else:
        p.write_text(json.dumps(payload, indent=1, sort_keys=True), encoding="utf-8")
    return p


#: The generated runner's shape, reduced to the two tokens the grader looks for.
#: The real one is produced by codebase-scaffolder from _EXPERIMENT_MODULE.
ENTRY_POINT_SRC = '''"""GENERATED by researchforge codebase-scaffolder."""
from rf_runtime import check_invalid_conditions, emit, seed_everything

SPEC = {"experiment_id": "%s"}
INVALID_CONDITIONS = SPEC.get("invalid_conditions") or []


def main(metrics):
    fired, unchecked = check_invalid_conditions(INVALID_CONDITIONS, metrics)
    emit({"status": "INVALID" if fired else "COMPLETED", "metrics": metrics})
'''

PRIMARY_VALUES = {1: 0.81, 2: 0.83, 3: 0.85}
ABLATED_VALUES = {1: 0.71, 2: 0.72, 3: 0.74}
PRIMARY_MEAN = 0.83
ABLATED_MEAN = 0.7233333333333334


def _spec_doc(experiment_id, claim_type, baseline, *, ablation_ref=None):
    """An ExperimentSpec of the shape research-blueprint-compiler emits.

    Carries one machine-evaluable invalid_condition alongside the prose ones,
    because rf_runtime returns a prose condition as *unchecked* and the rubric
    grades on what the run could actually enforce.
    """
    doc = {
        "experiment_id": experiment_id,
        "claim_type": claim_type,
        "hypothesis": "the mechanism raises the primary metric",
        "baseline": baseline,
        "candidate": {"description": "the method under test"},
        "datasets": [{"name": "fixture", "resolved": True}],
        "metrics": [{"name": "primary", "role": "decision"}],
        "seeds": [1, 2, 3],
        "resources": {"seeds": 3, "conditions": 2, "runs": 6},
        "invalid_conditions": [
            {"code": "PRIMARY_DEGENERATE", "metric": "primary", "op": "<=", "value": 0.0,
             "why": "a non-positive primary metric means the evaluator did not score the run"},
            {"code": "EVALUATOR_CHANGED_MID_RUN",
             "condition": "the evaluator digest differs between the first and last run",
             "why": "conditions scored by different evaluators are not comparable"},
        ],
    }
    if ablation_ref:
        doc["ablation_ref"] = ablation_ref
    return doc


def _ledger_entry(experiment_id, seed, value, entry_point):
    return {
        "run_id": "run-acceptance", "experiment_id": experiment_id,
        "attempt_id": f"{experiment_id}:seed={seed}", "seed": seed,
        "status": "COMPLETED", "metrics": {"primary": value},
        "artifacts": [{"path": entry_point, "role": "entry_point"}], "warnings": [],
        "provenance": {"skill": "experiment-runner", "entry_point": entry_point,
                       "declared_metrics": ["primary"], "executed": True,
                       "evaluator_version": "ev-1", "environment_digest": "env-1"},
    }


def build_project(root: Path) -> Path:
    """A minimal project that genuinely satisfies all eight dimensions.

    Minimal in the sense that removing any file below makes some dimension
    unmeasurable or failing — which is what the mutating tests then do.
    """
    root.mkdir(parents=True, exist_ok=True)

    # -- experiments -------------------------------------------------------
    _w(root, "experiments/E-001.yaml",
       [_spec_doc("E-001", "comparative",
                  {"kind": "locally_measured", "established": True,
                   "pinned_revision": "abc123", "reproduction_level": "RL3"})])
    _w(root, "experiments/E-ABL-001.yaml",
       [_spec_doc("E-ABL-001", "ablation",
                  {"kind": "own_full_method", "reproduction_level": "RL3"},
                  ablation_ref="AB-001")])
    _w(root, "experiments/ablation_plan.yaml", json.dumps({
        "mechanisms": [{"mechanism_id": "M-001", "claim": "the gate matters"}],
        "ablations": [{
            "ablation_id": "AB-001", "mechanism_id": "M-001", "claim": "the gate matters",
            "isolation_test": {"kind": "remove_mechanism"},
            "counterfactual_controls": [{"kind": "matched_compute"},
                                        {"kind": "randomized_mechanism"}],
            "seeds": [1, 2, 3],
        }],
    }))
    _w(root, "experiments/environment.lock", "numpy==1.26.4\nscipy==1.13.0\n")
    _w(root, "experiments/sandbox_manifest.json",
       {"profile": "strict", "isolation": "container",
        "untrusted_code_execution_allowed": True,
        "host": {"platform": "linux", "python": "3.11.9"}, "warnings": []})

    # -- code: the entry points whose source the grader reads --------------
    _w(root, "code/e_001/run.py", ENTRY_POINT_SRC % "E-001")
    _w(root, "code/e_abl_001/run.py", ENTRY_POINT_SRC % "E-ABL-001")

    # -- ledger ------------------------------------------------------------
    ledger = ([_ledger_entry("E-001", s, v, "code/e_001/run.py")
               for s, v in PRIMARY_VALUES.items()]
              + [_ledger_entry("E-ABL-001", s, v, "code/e_abl_001/run.py")
                 for s, v in ABLATED_VALUES.items()])
    _w(root, "experiment_ledger.jsonl", ledger)

    # -- comparison mode ---------------------------------------------------
    _w(root, "reproduction/comparison_mode.json", {
        "mode": "CM_MEASURED", "derived_from_level": "RL3",
        "admissible_idea_modes": ["extend_generalize", "explain_diagnose"],
        "forbidden_claim_patterns": ["state-of-the-art"],
        "disclosure_required": {"required": False, "text_template": "", "must_appear_in": []},
        "substitute_baseline": None, "approved_by": "operator",
        "autonomous_decision_id": None,
    })

    # -- analysis ----------------------------------------------------------
    _w(root, "analysis/analysis_results.json", {
        "run_id": "run-acceptance", "ledger_digest": "d0", "n_runs": 6,
        "n_successful": 6, "n_failed": 0, "failure_rate": 0.0,
        "confirmatory_metrics": ["primary"], "exploratory_metrics": [],
        "groups": [
            {"group_id": "E-001::primary", "branch": "E-001", "metric": "primary",
             "kind": "confirmatory", "seeds": [1, 2, 3],
             "values": list(PRIMARY_VALUES.values()), "n": 3, "mean": PRIMARY_MEAN,
             "ci95": [0.78, 0.88]},
            {"group_id": "E-ABL-001::primary", "branch": "E-ABL-001", "metric": "primary",
             "kind": "confirmatory", "seeds": [1, 2, 3],
             "values": list(ABLATED_VALUES.values()), "n": 3, "mean": ABLATED_MEAN,
             "ci95": [0.68, 0.76]},
        ],
        "reported": [{"reported_id": "r1", "group_id": "E-001::primary", "branch": "E-001",
                      "metric": "primary", "statistic": "mean", "value": PRIMARY_MEAN,
                      "claim_ids": ["C-001"]}],
    })
    _w(root, "analysis/stats_audit.json", {
        "run_id": "run-acceptance", "alpha": 0.05, "min_seeds_required": 3,
        "target_power": 0.8, "n_runs": 6, "control_branch": "E-001",
        "tests": [{
            "test_id": "s1::primary::E-001_vs_E-ABL-001", "metric": "primary",
            "branch_a": "E-001", "branch_b": "E-ABL-001", "n_a": 3, "n_b": 3,
            "p_raw": 0.004, "p_holm": 0.004, "significant_raw": True,
            "significant_corrected": True, "refusal": None,
            "effect_size": {"g": 3.9, "ci95": [1.2, 6.6], "refused": None},
            "power": {"achieved": 0.93},
        }],
        "multiple_comparison_correction": {
            "applied": False, "method": "none", "family_size": 1,
            "why": "a single hypothesis test was performed"},
        "findings": [], "severity_counts": {"BLOCKER": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0},
        "evidence_lock": {"blocked": False, "blocked_by": [], "blocked_metrics": [],
                          "blocked_branches": [], "blocked_claims": []},
    })

    # -- findings ----------------------------------------------------------
    _w(root, "findings.jsonl", [
        {"finding_id": "F-001", "kind": "effect", "statement": "the gate raises primary",
         "source_ids": ["meta_analysis"]}])
    _w(root, "findings/negative_findings.jsonl", [])

    # -- manuscript --------------------------------------------------------
    _w(root, "paper/manuscript_spine.json", {
        "thesis": "the gate raises the primary metric",
        "sections": ["Results"],
        "claims": [{"claim_id": "C-001", "section": "Results", "kind": "effect",
                    "statement": "the gate raises primary from 0.72 to 0.83",
                    "evidence": {"result_ids": ["E-001"]}}],
        "disclosure": {"required": False, "must_appear_in": []},
        "findings_not_in_evidence_graph": [],
    })
    _w(root, "paper/draft_manifest.json", {
        "target_venue": "acceptance", "comparison_mode": "CM_MEASURED",
        "sections": ["Results"],
        "paragraphs": [{"paragraph_index": 0, "section": "Results", "claim_id": "C-001",
                        "citations": [], "synthetic": False}],
        "claim_index": {"C-001": {"section": "Results", "evidence": {"result_ids": ["E-001"]},
                                  "paragraph_indices": [0]}},
        "unwritten_claims": [], "empty_sections": [],
        "disclosure": {"required": False, "text": "", "must_appear_in": [],
                       "inserted_in": [], "missing_sections": []},
        "every_paragraph_bound_to_a_claim": True,
        "_synthetic": False, "_note": None,
    })
    _w(root, "paper/main.tex",
       "\\section{Results}\n% claim: C-001\n"
       "The gated model reaches 0.83 on the primary metric against 0.72 ablated.\n")
    _w(root, "paper/figure_plan.json", {
        "figures": [{"figure_id": "F-01", "claim_id": "C-001", "caption": "primary by branch"}]})

    # -- figures -----------------------------------------------------------
    _w(root, "figures/selected/f-01.svg",
       '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="120">'
       '<g id="fig-f-01-e-001-mean"><text x="5" y="15">primary</text></g></svg>')
    _w(root, "figures/selected/_manifest.json", {
        "figures": [{"figure_id": "F-01", "claim_id": "C-001", "file": "f-01.svg",
                     "form": "per_seed_scatter", "caption": "primary by branch"}],
        "target_venue": "acceptance", "format": "svg", "rasterized": False})
    _w(root, "figures/element_map.json", {
        "figures": {"F-01": {
            "file": "f-01.svg", "claim_id": "C-001", "form": "per_seed_scatter",
            "elements": [
                {"element_id": "fig-f-01-e-001-mean", "role": "mean",
                 "binds_to": {"artifact": "analysis_results", "group_id": "E-001::primary",
                              "statistic": "mean"},
                 "values": [PRIMARY_MEAN]},
                {"element_id": "fig-f-01-e-001-n", "role": "sample_size",
                 "binds_to": {"artifact": "analysis_results", "group_id": "E-001::primary",
                              "statistic": "n"},
                 "values": [3.0]},
                {"element_id": "fig-f-01-title", "role": "title",
                 "binds_to": {"artifact": "manuscript_spine", "claim_id": "C-001"},
                 "values": []},
            ]}},
        "binding_rule": "every element that carries a number names its source"})

    # -- audits ------------------------------------------------------------
    _w(root, "review/claim_audit.jsonl", [
        {"claim_id": "C-001", "locator": "Results#p0", "section": "Results",
         "text": "The gated model reaches 0.83 on the primary metric against 0.72 ablated.",
         "quantitative": True, "citations": [], "resolved_citations": [],
         "unresolved_citations": [], "supporting_edges": ["E-001"],
         "number_checks": [{"value": "0.83", "matched": True, "ledger_entry": "E-001"},
                           {"value": "0.72", "matched": True, "ledger_entry": "E-ABL-001"}],
         "verdict": "SUPPORTED", "reason": "", "remediation": ""},
    ])
    _w(root, "review/integrity_gate.json", {
        "verdict": "PASS", "submission_permitted": True, "run_id": "run-acceptance",
        "comparison_mode": "CM_MEASURED",
        "counts": {"SUPPORTED": 1, "PARTIALLY_SUPPORTED": 0, "NOT_SUPPORTED": 0,
                   "FABRICATED": 0, "SCOPE_MISMATCH": 0, "NOT_A_CLAIM": 0},
        "checks": [], "blockers": [], "model_consulted": False,
        "synthetic_inputs": False, "human_reviewed": False})
    _w(root, "review/review_report.json", {
        "target_venue": "acceptance", "recommendation": "REVISE_THEN_SUBMIT",
        "submission_permitted_by_integrity_gate": True, "simulated_reviews": [],
        "grounded_points": [], "evidence_coverage": {"claims_in_spine": 1}})

    # -- release + provenance ----------------------------------------------
    released = ["manuscript_draft", "claim_audit", "integrity_gate", "experiment_ledger"]
    _w(root, "release/release_manifest.json", {
        "project_id": root.name, "run_id": "run-acceptance",
        "release_status": "ASSISTED_DRAFT", "released": True, "submission_ready": False,
        "provenance_complete": True,
        "artifacts": [{"artifact_id": a, "path": f"x/{a}", "sha256": "0" * 64,
                       "kind": "deliverable", "parents": [], "producer": "s",
                       "provenance_events": 1, "provenance_complete": True, "released": True}
                      for a in released],
        "blockers": [],
        "integrity_gate": {"verdict": "PASS", "submission_permitted": True, "blockers": 0},
        "comparison_mode": {"mode": "CM_MEASURED", "derived_from_level": "RL3",
                            "disclosure_required": False}})
    _w(root, "provenance.jsonl", [
        {"kind": "artifact_write", "skill": "experiment-runner",
         "artifact_id": "experiment_ledger", "digest": "0" * 64, "detail": {}}])
    _w(root, ".researchforge/research_state.json",
       {"state": "RELEASED", "run_id": "run-acceptance"})
    return root


def run_grade(project: Path, second: Path | None = None):
    return grade_mod.grade(project, REPO, second)


def outcomes(result):
    return {d["id"]: d["outcome"] for d in result["dimensions"]}


def check(result, dim_id, check_id):
    for d in result["dimensions"]:
        if d["id"] == dim_id:
            for c in d["checks"]:
                if c["id"] == check_id:
                    return c
    raise AssertionError(f"{dim_id}/{check_id} not in the report")


# --------------------------------------------------------------------------
# the passing baseline
# --------------------------------------------------------------------------
def test_a_project_that_satisfies_every_dimension_is_accepted(tmp_path):
    project = build_project(tmp_path / "p")
    second = tmp_path / "p-second"
    # Same inputs, same outputs: this is what the determinism dimension asks for,
    # and it must be supplied rather than assumed.
    shutil.copytree(project, second)

    result = run_grade(project, second)
    assert result["verdict"] == "ACCEPTED", (
        f"{result['verdict_reason']}\n"
        + json.dumps([c for d in result["dimensions"] for c in d["checks"]
                      if c["outcome"] not in ("PASS", "NOT_APPLICABLE")], indent=1))
    assert result["failed_dimensions"] == []
    assert result["not_measured_dimensions"] == []
    assert len(result["dimensions"]) == 8
    assert all(o in ("PASS", "NOT_APPLICABLE") for o in outcomes(result).values())


def test_without_a_second_run_reproducibility_is_not_measured_and_blocks_acceptance(tmp_path):
    project = build_project(tmp_path / "p")
    result = run_grade(project)
    assert outcomes(result)["reproducibility"] == "NOT_MEASURED"
    # The distinction the whole grader turns on: nothing failed, and it is still
    # not accepted.
    assert result["failed_dimensions"] == []
    assert result["verdict"] == "INCOMPLETE"


# --------------------------------------------------------------------------
# refusals
# --------------------------------------------------------------------------
def test_a_fabricated_claim_fails_evidence_support(tmp_path):
    project = build_project(tmp_path / "p")
    audit = [json.loads(l) for l in
             (project / "review/claim_audit.jsonl").read_text().splitlines() if l.strip()]
    audit.append({
        "claim_id": "C-002", "locator": "Results#p1", "section": "Results",
        "text": "Throughput improved by 41.7%.", "quantitative": True,
        "citations": [], "resolved_citations": [], "unresolved_citations": [],
        "supporting_edges": [], "number_checks": [{"value": "41.7", "matched": False,
                                                   "ledger_entry": None}],
        "verdict": "FABRICATED",
        "reason": "the number matches no recorded metric", "remediation": "delete it"})
    _w(project, "review/claim_audit.jsonl", audit)
    gate = json.loads((project / "review/integrity_gate.json").read_text())
    gate["counts"]["FABRICATED"] = 1
    gate["verdict"] = "BLOCK"
    _w(project, "review/integrity_gate.json", gate)

    result = run_grade(project, project)
    assert outcomes(result)["evidence_support"] == "FAIL"
    assert result["verdict"] == "REJECTED"
    assert check(result, "evidence_support", "E4.1_zero_fabricated")["outcome"] == "FAIL"
    # The untraced number is reported too — the same defect seen from the other side.
    assert check(result, "evidence_support",
                 "E4.3_quantitative_claims_traced")["outcome"] == "FAIL"


def test_a_figure_bound_to_no_spine_claim_fails_figures(tmp_path):
    project = build_project(tmp_path / "p")
    manifest = json.loads((project / "figures/selected/_manifest.json").read_text())
    manifest["figures"].append({"figure_id": "F-02", "claim_id": "C-999",
                                "file": "f-01.svg", "form": "per_seed_scatter",
                                "caption": "an argument the paper does not make"})
    _w(project, "figures/selected/_manifest.json", manifest)

    result = run_grade(project, project)
    assert outcomes(result)["figures"] == "FAIL"
    binding = check(result, "figures", "E6.2_figure_claim_binding")
    assert binding["outcome"] == "FAIL"
    assert binding["measured"] == 0.5 and binding["threshold"] == 1.0
    assert result["verdict"] == "REJECTED"


def test_a_raster_hidden_inside_an_svg_fails_figures(tmp_path):
    project = build_project(tmp_path / "p")
    _w(project, "figures/selected/f-01.svg",
       '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="120">'
       '<image href="data:image/png;base64,iVBORw0KGgo=" width="200" height="120"/></svg>')
    result = run_grade(project, project)
    assert check(result, "figures", "E6.1_vector_not_raster")["outcome"] == "FAIL"
    assert outcomes(result)["figures"] == "FAIL"


def test_an_absent_audit_is_not_measured_rather_than_passed(tmp_path):
    project = build_project(tmp_path / "p")
    (project / "analysis/stats_audit.json").unlink()

    result = run_grade(project, project)
    o = outcomes(result)
    assert o["statistical_validity"] == "NOT_MEASURED"
    # It is not a FAIL either: the grader has no evidence the statistics are wrong,
    # only that it cannot see them.
    assert result["failed_dimensions"] == []
    assert "statistical_validity" in result["not_measured_dimensions"]
    assert result["verdict"] == "INCOMPLETE"
    assert check(result, "statistical_validity",
                 "E5.stats_audit_present")["outcome"] == "NOT_MEASURED"


def test_an_absent_claim_audit_is_not_measured_rather_than_passed(tmp_path):
    project = build_project(tmp_path / "p")
    (project / "review/claim_audit.jsonl").unlink()
    result = run_grade(project, project)
    assert outcomes(result)["evidence_support"] == "NOT_MEASURED"
    assert result["verdict"] == "INCOMPLETE"


def test_a_synthetic_project_is_refused_not_scored(tmp_path):
    project = build_project(tmp_path / "p")
    manifest = json.loads((project / "paper/draft_manifest.json").read_text())
    manifest["_synthetic"] = True
    _w(project, "paper/draft_manifest.json", manifest)

    result = run_grade(project, project)
    assert result["verdict"] == "REFUSED_SYNTHETIC"
    # No dimension is scored at all. A partial score on stub output is still a
    # score, and it would outlive the caveat printed beside it.
    assert result["dimensions"] == []
    assert any("draft_manifest" in h for h in result["synthetic_markers"])


def test_a_false_synthetic_flag_is_not_a_refusal(tmp_path):
    """`"_synthetic": false` is the runtime saying the opposite of the marker."""
    project = build_project(tmp_path / "p")
    result = run_grade(project, project)
    assert result["verdict"] != "REFUSED_SYNTHETIC"


# --------------------------------------------------------------------------
# the measurements nothing upstream makes
# --------------------------------------------------------------------------
def test_a_mechanism_with_no_executed_ablation_fails_ablation_coverage(tmp_path):
    project = build_project(tmp_path / "p")
    plan = json.loads((project / "experiments/ablation_plan.yaml").read_text())
    plan["mechanisms"].append({"mechanism_id": "M-002", "claim": "the router matters"})
    plan["ablations"].append({
        "ablation_id": "AB-002", "mechanism_id": "M-002", "claim": "the router matters",
        "isolation_test": {"kind": "remove_mechanism"},
        "counterfactual_controls": [{"kind": "matched_compute"}], "seeds": [1, 2, 3]})
    _w(project, "experiments/ablation_plan.yaml", json.dumps(plan))

    result = run_grade(project, project)
    cov = check(result, "ablations", "E3.1_isolation_test_per_mechanism")
    assert cov["outcome"] == "FAIL"
    assert cov["measured"] == 0.5
    assert outcomes(result)["ablations"] == "FAIL"


def test_an_ablation_measured_on_its_own_metric_fails(tmp_path):
    """The shape a retried null takes, and a contrast nobody can compute either way."""
    project = build_project(tmp_path / "p")
    specs = json.loads((project / "experiments/E-ABL-001.yaml").read_text())
    specs[0]["metrics"] = [{"name": "mechanism_activation", "role": "decision"}]
    _w(project, "experiments/E-ABL-001.yaml", specs)
    ledger = [json.loads(l) for l in
              (project / "experiment_ledger.jsonl").read_text().splitlines() if l.strip()]
    for e in ledger:
        if e["experiment_id"] == "E-ABL-001":
            e["metrics"] = {"mechanism_activation": e["metrics"]["primary"]}
            e["provenance"]["declared_metrics"] = ["mechanism_activation"]
    _w(project, "experiment_ledger.jsonl", ledger)

    result = run_grade(project, project)
    c = check(result, "ablations",
              "E3.3a_ablation_shares_a_metric_with_its_primary_experiment")
    assert c["outcome"] == "FAIL"
    assert outcomes(result)["ablations"] == "FAIL"


def test_a_null_ablation_that_appears_in_no_finding_fails(tmp_path):
    project = build_project(tmp_path / "p")
    stats = json.loads((project / "analysis/stats_audit.json").read_text())
    # The isolation came back flat. That is a result, and it is owed to the reader.
    stats["tests"][0]["significant_corrected"] = False
    stats["tests"][0]["p_holm"] = 0.42
    _w(project, "analysis/stats_audit.json", stats)

    result = run_grade(project, project)
    assert check(result, "ablations", "E3.3b_null_results_reported")["outcome"] == "FAIL"

    _w(project, "findings/negative_findings.jsonl", [
        {"finding_id": "NEG-001", "kind": "no_effect", "metric": "primary",
         "contrast": "E-001 vs E-ABL-001", "branch": "E-ABL-001",
         "statement": "removing M-001 does not move primary beyond seed dispersion",
         "evidence": {"artifacts": ["meta_analysis"]}}])
    again = run_grade(project, project)
    assert check(again, "ablations", "E3.3b_null_results_reported")["outcome"] == "PASS"


def test_too_few_completed_seeds_for_a_comparative_claim_fails(tmp_path):
    project = build_project(tmp_path / "p")
    ledger = [json.loads(l) for l in
              (project / "experiment_ledger.jsonl").read_text().splitlines() if l.strip()]
    # Two seeds instead of three: below the point where dispersion is estimable,
    # which is what the comparative claim is measured against.
    ledger = [e for e in ledger if not (e["experiment_id"] == "E-001" and e["seed"] == 3)]
    _w(project, "experiment_ledger.jsonl", ledger)

    result = run_grade(project, project)
    seeds = check(result, "experiment_engineering", "E1.4_seed_adequacy")
    assert seeds["outcome"] == "FAIL"
    assert seeds["threshold"] == {"inferential": 3, "descriptive": 2}
    assert outcomes(result)["experiment_engineering"] == "FAIL"


def test_a_metric_the_spec_never_declared_fails_experiment_engineering(tmp_path):
    project = build_project(tmp_path / "p")
    ledger = [json.loads(l) for l in
              (project / "experiment_ledger.jsonl").read_text().splitlines() if l.strip()]
    ledger[0]["metrics"]["throughput"] = 41.7
    _w(project, "experiment_ledger.jsonl", ledger)

    result = run_grade(project, project)
    m = check(result, "experiment_engineering", "E1.3_metrics_declared")
    assert m["outcome"] == "FAIL" and m["threshold"] == 0


def test_prose_only_invalid_conditions_are_reported_as_unenforced(tmp_path):
    project = build_project(tmp_path / "p")
    specs = json.loads((project / "experiments/E-001.yaml").read_text())
    specs[0]["invalid_conditions"] = [
        {"code": "CONDITIONS_NOT_MATCHED",
         "condition": "any factor other than the declared difference varied",
         "why": "the difference measured is then not the difference specified"}]
    _w(project, "experiments/E-001.yaml", specs)

    result = run_grade(project, project)
    assert check(result, "experiment_engineering",
                 "E1.5a_invalid_conditions_declared")["outcome"] == "PASS"
    assert check(result, "experiment_engineering",
                 "E1.5b_invalid_conditions_machine_evaluable")["outcome"] == "FAIL"


def test_a_missing_entry_point_makes_the_runtime_guard_unmeasurable(tmp_path):
    project = build_project(tmp_path / "p")
    (project / "code/e_001/run.py").unlink()
    result = run_grade(project, project)
    c = check(result, "experiment_engineering", "E1.5c_invalid_conditions_checked_at_runtime")
    assert c["outcome"] == "NOT_MEASURED"
    assert outcomes(result)["experiment_engineering"] == "NOT_MEASURED"


def test_a_figure_number_that_disagrees_with_the_analysis_fails(tmp_path):
    project = build_project(tmp_path / "p")
    em = json.loads((project / "figures/element_map.json").read_text())
    em["figures"]["F-01"]["elements"][0]["values"] = [0.91]
    _w(project, "figures/element_map.json", em)

    result = run_grade(project, project)
    assert check(result, "figures", "E6.3_figure_numbers_match_analysis")["outcome"] == "FAIL"


def test_a_spine_claim_the_draft_never_argues_fails_writing(tmp_path):
    project = build_project(tmp_path / "p")
    spine = json.loads((project / "paper/manuscript_spine.json").read_text())
    spine["claims"].append({"claim_id": "C-002", "section": "Results", "kind": "effect",
                            "statement": "the router also matters",
                            "evidence": {"result_ids": ["E-002"]}})
    _w(project, "paper/manuscript_spine.json", spine)

    result = run_grade(project, project)
    c = check(result, "writing", "E7.2_spine_claims_are_the_drafts_claims")
    assert c["outcome"] == "FAIL"
    assert c["measured"]["only_in_spine"] == 1


def test_forbidden_claim_language_in_the_rendered_draft_fails_writing(tmp_path):
    project = build_project(tmp_path / "p")
    _w(project, "paper/main.tex",
       "\\section{Results}\n% claim: C-001\n"
       "Our gated model is state-of-the-art on the primary metric.\n")
    result = run_grade(project, project)
    assert check(result, "writing", "E7.4_no_forbidden_claim_pattern")["outcome"] == "FAIL"


def test_a_partially_supported_manuscript_fails_the_support_ratio(tmp_path):
    """The gap this ratio exists to close: the gate passes, the argument does not."""
    project = build_project(tmp_path / "p")
    audit = [json.loads(l) for l in
             (project / "review/claim_audit.jsonl").read_text().splitlines() if l.strip()]
    for i in range(4):
        audit.append({**audit[0], "claim_id": f"C-10{i}", "locator": f"Results#p{i + 1}",
                      "quantitative": False, "number_checks": [],
                      "verdict": "PARTIALLY_SUPPORTED",
                      "reason": "the claim is broader than the evidence behind it"})
    _w(project, "review/claim_audit.jsonl", audit)
    gate = json.loads((project / "review/integrity_gate.json").read_text())
    gate["counts"] = {"SUPPORTED": 1, "PARTIALLY_SUPPORTED": 4, "NOT_SUPPORTED": 0,
                      "FABRICATED": 0, "SCOPE_MISMATCH": 0, "NOT_A_CLAIM": 0}
    # The integrity gate is content: PARTIALLY_SUPPORTED is not a blocking verdict.
    gate["verdict"] = "PASS_WITH_CONDITIONS"
    gate["submission_permitted"] = True
    _w(project, "review/integrity_gate.json", gate)

    result = run_grade(project, project)
    ratio = check(result, "evidence_support", "E4.2_support_ratio")
    assert ratio["outcome"] == "FAIL"
    assert ratio["measured"] == 0.2 and ratio["threshold"] == 0.95
    assert check(result, "evidence_support", "E4.1_zero_fabricated")["outcome"] == "PASS"


def test_a_refused_release_is_not_an_accepted_one(tmp_path):
    project = build_project(tmp_path / "p")
    rm = json.loads((project / "release/release_manifest.json").read_text())
    rm["released"] = False
    rm["release_status"] = "BLOCKED"
    for a in rm["artifacts"]:
        a["released"] = False
    _w(project, "release/release_manifest.json", rm)

    result = run_grade(project, project)
    c = check(result, "reproducibility", "E8.1_provenance_for_every_released_artifact")
    assert c["outcome"] == "FAIL"
    assert outcomes(result)["reproducibility"] == "FAIL"


def test_a_second_run_that_produced_different_numbers_fails(tmp_path):
    project = build_project(tmp_path / "p")
    second = tmp_path / "p-second"
    shutil.copytree(project, second)
    ledger = [json.loads(l) for l in
              (second / "experiment_ledger.jsonl").read_text().splitlines() if l.strip()]
    ledger[0]["metrics"]["primary"] = 0.9999
    _w(second, "experiment_ledger.jsonl", ledger)

    result = run_grade(project, second)
    c = check(result, "reproducibility", "E8.3_second_run_reaches_the_same_state")
    assert c["outcome"] == "FAIL"
    assert c["measured"]["runs_match"] is False


def test_a_baseline_neither_pinned_nor_declared_unpinned_fails(tmp_path):
    project = build_project(tmp_path / "p")
    specs = json.loads((project / "experiments/E-001.yaml").read_text())
    specs[0]["baseline"] = {"kind": "locally_measured", "established": False,
                            "pinned_revision": None}
    _w(project, "experiments/E-001.yaml", specs)

    result = run_grade(project, project)
    c = check(result, "baselines", "E2.2_baseline_pinned_or_declared_unpinned")
    assert c["outcome"] == "FAIL"

    # Declaring it is enough. The rubric does not demand a pinned baseline; it
    # demands that the project knows which of the two it has.
    specs[0]["invalid_conditions"].append({
        "code": "BASELINE_NOT_ESTABLISHED",
        "condition": "the baseline has no pinned revision at run time",
        "why": "an unpinned baseline can silently change between conditions"})
    _w(project, "experiments/E-001.yaml", specs)
    again = run_grade(project, project)
    assert check(again, "baselines",
                 "E2.2_baseline_pinned_or_declared_unpinned")["outcome"] == "PASS"


def test_a_comparative_spec_under_cm_none_fails_the_mode_check(tmp_path):
    project = build_project(tmp_path / "p")
    cm = json.loads((project / "reproduction/comparison_mode.json").read_text())
    cm["mode"] = "CM_NONE"
    cm["derived_from_level"] = "RL0"
    _w(project, "reproduction/comparison_mode.json", cm)

    result = run_grade(project, project)
    c = check(result, "baselines", "E2.3_comparison_permitted_by_mode")
    assert c["outcome"] == "FAIL"
    assert c["measured"]["mode"] == "CM_NONE"


# --------------------------------------------------------------------------
# outputs and the operator surface
# --------------------------------------------------------------------------
def test_both_report_files_are_written_and_the_exit_code_matches_the_verdict(tmp_path):
    project = build_project(tmp_path / "p")
    second = tmp_path / "p-second"
    shutil.copytree(project, second)
    out = tmp_path / "out"
    rc = grade_mod.main([str(project), "--second-run", str(second),
                         "--repo-root", str(REPO), "--out", str(out), "--quiet"])
    assert rc == 0
    result = json.loads((out / "acceptance_result.json").read_text())
    assert result["verdict"] == "ACCEPTED"
    report = (out / "acceptance_report.md").read_text()
    assert "# Acceptance report — ACCEPTED" in report
    # Every dimension is named in the human report, including the ones that passed:
    # a report that lists only failures cannot be checked for completeness.
    for d in result["dimensions"]:
        assert d["id"] in report


def test_a_refused_grade_exits_three_and_says_why(tmp_path, capsys):
    rc = grade_mod.main([str(tmp_path / "p"), "--repo-root", str(tmp_path), "--quiet"])
    assert rc == 3
    assert "artifact contract" in capsys.readouterr().err


def test_the_grader_refuses_when_its_threshold_copies_drift(tmp_path, monkeypatch):
    """A grader holding a stale threshold grades against a rule nobody agreed to."""
    pytest.importorskip("researchforge.skills.analysis")
    project = build_project(tmp_path / "p")
    monkeypatch.setattr(grade_mod, "MIN_SEEDS_INFERENTIAL", 2)
    with pytest.raises(grade_mod.GraderRefusal) as e:
        run_grade(project, project)
    assert "drifted" in str(e.value)
