#!/usr/bin/env python3
"""Single source of truth -> two typed SDKs.

manifests/artifact-graph.json is the contract. This generates:
  packages/contracts/src/generated.ts   (TypeScript)
  python/researchforge/generated.py     (Python)

Neither is hand-edited. If the manifest and the code disagree, the code is wrong.
This is the entire justification for the TypeScript orchestration layer: the
cross-language boundary is the one place a contract violation would otherwise go
unnoticed, so the boundary is generated from the contract rather than described
by it.
"""
import json, pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
G = json.loads((ROOT/'manifests/artifact-graph.json').read_text())
C = json.loads((ROOT/'manifests/skill-catalog.json').read_text())
ART, DEPS = G['artifacts'], G['depends_on']
CONS, INTERNAL = G['consumers'], G.get('internal_artifacts', {})
SKILLS = [s['name'] for s in C['skills']]
STATES = C['states']

def pyname(s): return re.sub(r'[^0-9a-zA-Z]+', '_', s).upper()
def tsname(s): return ''.join(p.capitalize() for p in re.split(r'[^0-9a-zA-Z]+', s) if p)

banner = ("// GENERATED by tools/codegen/generate.py from manifests/artifact-graph.json\n"
          "// Do not edit. Run `npm run codegen` (or python tools/codegen/generate.py).\n")
pybanner = ('"""GENERATED by tools/codegen/generate.py from manifests/artifact-graph.json.\n\n'
            'Do not edit. Run `python tools/codegen/generate.py`.\n"""\n')

# ---------------- TypeScript ----------------
ts = [banner]
ts.append("export const ARTIFACT_IDS = [\n" + "".join(f"  {json.dumps(a)},\n" for a in sorted(ART)) + "] as const;")
ts.append("export type ArtifactId = (typeof ARTIFACT_IDS)[number];\n")
ts.append("export const SKILL_NAMES = [\n" + "".join(f"  {json.dumps(s)},\n" for s in SKILLS) + "] as const;")
ts.append("export type SkillName = (typeof SKILL_NAMES)[number];\n")
ts.append("export const STATES = [\n" + "".join(f"  {json.dumps(s)},\n" for s in STATES) + "] as const;")
ts.append("export type RunState = (typeof STATES)[number];\n")
ts.append("export interface ArtifactSpec {\n  readonly producer: SkillName;\n  readonly path: string;\n"
          "  readonly schema: string | null;\n  readonly description: string;\n}\n")
ts.append("export const ARTIFACTS: Readonly<Record<ArtifactId, ArtifactSpec>> = {")
for a in sorted(ART):
    v = ART[a]
    ts.append(f"  {json.dumps(a)}: {{ producer: {json.dumps(v['producer'])}, path: {json.dumps(v['path'])}, "
              f"schema: {json.dumps(v['schema'])}, description: {json.dumps(v['description'])} }},")
ts.append("} as const;\n")
ts.append("export interface SkillContract {\n  readonly consumes: readonly ArtifactId[];\n"
          "  readonly produces: readonly ArtifactId[];\n  readonly external: readonly string[];\n"
          "  readonly feedback: readonly ArtifactId[];\n  readonly dependsOn: readonly SkillName[];\n}\n")
ts.append("export const SKILLS: Readonly<Record<SkillName, SkillContract>> = {")
for s in SKILLS:
    c = CONS.get(s, {"artifacts": [], "external": [], "feedback": []})
    prod = sorted([a for a in ART if ART[a]['producer'] == s])
    ts.append(f"  {json.dumps(s)}: {{ consumes: {json.dumps(c['artifacts'])}, produces: {json.dumps(prod)}, "
              f"external: {json.dumps(c['external'])}, feedback: {json.dumps(c['feedback'])}, "
              f"dependsOn: {json.dumps(DEPS.get(s, []))} }},")
ts.append("} as const;\n")
ts.append("/** Topological order of the research run, derived from the contract, not hand-listed. */")
order, seen = [], set()
def visit(n):
    if n in seen: return
    seen.add(n)
    for d in DEPS.get(n, []): visit(d)
    order.append(n)
for s in SKILLS: visit(s)
ts.append("export const BUILD_ORDER = [\n" + "".join(f"  {json.dumps(s)},\n" for s in order) + "] as const;\n")
(ROOT/'packages/contracts/src/generated.ts').write_text("\n".join(ts))

# ---------------- Python ----------------
py = [pybanner, "from __future__ import annotations", "from dataclasses import dataclass",
      "from typing import Final\n"]
py.append("@dataclass(frozen=True)\nclass ArtifactSpec:\n    producer: str\n    path: str\n"
          "    schema: str | None\n    description: str\n")
py.append("ARTIFACTS: Final[dict[str, ArtifactSpec]] = {")
for a in sorted(ART):
    v = ART[a]
    py.append(f"    {json.dumps(a)}: ArtifactSpec({v['producer']!r}, {v['path']!r}, "
              f"{v['schema']!r}, {v['description']!r}),")
py.append("}\n")
py.append("@dataclass(frozen=True)\nclass SkillContract:\n    consumes: tuple[str, ...]\n"
          "    produces: tuple[str, ...]\n    external: tuple[str, ...]\n    feedback: tuple[str, ...]\n"
          "    depends_on: tuple[str, ...]\n")
py.append("SKILLS: Final[dict[str, SkillContract]] = {")
for s in SKILLS:
    c = CONS.get(s, {"artifacts": [], "external": [], "feedback": []})
    prod = sorted([a for a in ART if ART[a]['producer'] == s])
    py.append(f"    {json.dumps(s)}: SkillContract({tuple(c['artifacts'])!r}, {tuple(prod)!r}, "
              f"{tuple(c['external'])!r}, {tuple(c['feedback'])!r}, {tuple(DEPS.get(s, []))!r}),")
py.append("}\n")
py.append(f"STATES: Final[tuple[str, ...]] = {tuple(STATES)!r}\n")
py.append(f"BUILD_ORDER: Final[tuple[str, ...]] = {tuple(order)!r}\n")
py.append("#: artifact -> spec, for artifacts that never cross a skill boundary.")
py.append("#: They are still written to disk and still carry provenance; they are simply")
py.append("#: not part of the public contract, so no other skill may depend on them.")
py.append("INTERNAL_ARTIFACT_SPECS: Final[dict[str, dict[str, ArtifactSpec]]] = {")
for k, v in sorted(INTERNAL.items()):
    py.append(f"    {json.dumps(k)}: {{")
    for a, sp in sorted(v.items()):
        py.append(f"        {json.dumps(a)}: ArtifactSpec({json.dumps(k)}, {sp['path']!r}, "
                  f"{sp['schema']!r}, {sp['description']!r}),")
    py.append("    },")
py.append("}\n")
py.append("INTERNAL_ARTIFACTS: Final[dict[str, tuple[str, ...]]] = "
          "{k: tuple(v) for k, v in INTERNAL_ARTIFACT_SPECS.items()}\n")
py.append('CONTRACT_DIGEST: Final[str] = "%s"\n' % __import__('hashlib').sha256(
    (ROOT/'manifests/artifact-graph.json').read_bytes()).hexdigest()[:16])
(ROOT/'python/researchforge/generated.py').write_text("\n".join(py))

print(f"generated: {len(ART)} artifacts, {len(SKILLS)} skills, {len(STATES)} states, "
      f"build order {len(order)}")
