"""GENERATED by tools/codegen/generate.py from manifests/artifact-graph.json.

Do not edit. Run `python tools/codegen/generate.py`.
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Final

@dataclass(frozen=True)
class ArtifactSpec:
    producer: str
    path: str
    schema: str | None
    description: str

ARTIFACTS: Final[dict[str, ArtifactSpec]] = {
    "acceptance_criteria": ArtifactSpec('research-blueprint-compiler', 'experiments/acceptance_criteria.md', None, 'What counts as success/failure'),
    "analogy_candidates": ArtifactSpec('idea-seed-miner', 'ideas/analogy_candidates.jsonl', None, 'Cross-domain mechanism transfers'),
    "analysis_code": ArtifactSpec('data-analyst', 'analysis/analysis.py|ipynb', None, 'Reproducible analysis script'),
    "analysis_plots": ArtifactSpec('data-analyst', 'analysis/plots/', None, 'Diagnostic plots'),
    "analysis_report": ArtifactSpec('data-analyst', 'analysis/analysis_report.md', None, 'Analyst-grade narrative'),
    "analysis_results": ArtifactSpec('data-analyst', 'analysis/analysis_results.json', None, 'Computed results'),
    "artifact_manifest": ArtifactSpec('experiment-runner', 'artifact_manifest.json', 'ArtifactManifest', 'Manifest of all project artifacts'),
    "assumption_tests": ArtifactSpec('idea-seed-miner', 'ideas/assumption_tests.jsonl', None, 'Cheap probes that would falsify assumptions'),
    "baseline_assets": ArtifactSpec('result-reproducer', 'baseline/baseline_assets.json', None, 'Pinned repo/data/checkpoint locations'),
    "baseline_deviation_log": ArtifactSpec('result-reproducer', 'baseline/deviation_log.md', None, 'Deviations from published setup'),
    "baseline_license_risk": ArtifactSpec('result-reproducer', 'baseline/license_risk.md', None, 'License and reuse constraints'),
    "baseline_metrics": ArtifactSpec('result-reproducer', 'baseline/baseline_metrics.json', None, 'Locally measured baseline numbers'),
    "baseline_repo_rankings": ArtifactSpec('result-reproducer', 'baseline/repo_rankings.json', None, 'Ranked candidate code repositories'),
    "benchmark_matrix": ArtifactSpec('literature-search', 'literature/benchmark_matrix.csv', None, 'Benchmarks x reported results'),
    "best_candidate": ArtifactSpec('experiment-runner', 'experiments/best_candidate.json', None, 'Best surviving candidate'),
    "bibliography": ArtifactSpec('citation-resolver', 'paper/references.bib', None, 'Rendered bibliography'),
    "blueprint_dag": ArtifactSpec('research-blueprint-compiler', 'experiments/dag.json', None, 'Stage dependency DAG'),
    "boundary_conditions": ArtifactSpec('finding-memory', 'findings/boundary_conditions.md', None, 'Where the method stops working'),
    "branch_map": ArtifactSpec('project-repo-manager', '.researchforge/branch_map.json', None, 'Idea/experiment -> branch mapping'),
    "checkpoint_metadata": ArtifactSpec('project-repo-manager', '.researchforge/checkpoints.jsonl', None, 'Resumable milestone checkpoints'),
    "citation_audit": ArtifactSpec('claim-citation-auditor', 'review/citation_audit.md', None, 'Citation support report'),
    "citation_clusters": ArtifactSpec('citation-resolver', 'literature/neighbor_clusters.json', None, 'Topical clusters of neighbors'),
    "citation_gap_candidates": ArtifactSpec('citation-resolver', 'literature/gap_candidates.jsonl', None, 'Under-explored regions of the graph'),
    "citation_graph": ArtifactSpec('citation-resolver', 'literature/citation_graph.json', None, 'Forward/backward citation graph'),
    "citation_resolution_report": ArtifactSpec('citation-resolver', 'literature/resolution_report.md', None, 'Unresolved/ambiguous reference report'),
    "claim_audit": ArtifactSpec('claim-citation-auditor', 'review/claim_audit.jsonl', None, 'Per-claim support verdicts'),
    "claim_registry": ArtifactSpec('claim-evidence-graph', 'evidence/claim_registry.json', None, 'Registry of extracted claims'),
    "closest_prior_work": ArtifactSpec('idea-evaluator', 'ideas/closest_prior_work.jsonl', None, 'Nearest prior work with delta table'),
    "code_tests": ArtifactSpec('codebase-scaffolder', 'code/tests/', None, 'Tests for generated code'),
    "code_worktree": ArtifactSpec('codebase-scaffolder', 'code/', None, 'Generated code branch/worktree'),
    "comparison_mode": ArtifactSpec('reproduction-fallback-planner', 'reproduction/comparison_mode.json', 'ComparisonMode', 'Which comparative claims the project is allowed to make, derived from RL'),
    "contribution_atoms": ArtifactSpec('paper-model-builder', 'evidence/contribution_atoms.json', None, 'Atomic contributions of the source paper'),
    "coverage_report": ArtifactSpec('literature-provider-manager', 'literature/coverage_report.json', None, 'Measured retrieval coverage and its known blind spots'),
    "debug_terminal_status": ArtifactSpec('codebase-scaffolder', 'experiments/terminal_status.json', None, 'Terminal classification preventing retry loops'),
    "decision_log": ArtifactSpec('user-feedback-gate', 'ideas/decision_log.jsonl', None, 'Selection/merge/reject history'),
    "deck_manifest": ArtifactSpec('deck-factory', 'slides/deck_manifest.json', None, 'Deck contents and provenance'),
    "defense_deck": ArtifactSpec('deck-factory', 'slides/defense.pptx', None, 'Native editable defense deck'),
    "draft_manifest": ArtifactSpec('manuscript-builder', 'paper/draft_manifest.json', None, 'Claim -> section -> evidence index'),
    "editable_svg": ArtifactSpec('figure-factory', 'figures/editable/', None, 'Editable vector version of a figure'),
    "environment_lock": ArtifactSpec('sandbox-provisioner', 'experiments/environment.lock', None, 'Pinned package/system versions'),
    "eval_failure_taxonomy": ArtifactSpec('research-eval-harness', 'evals/failure_taxonomy.md', None, 'Recurring system failure modes'),
    "eval_runs": ArtifactSpec('research-eval-harness', 'evals/eval_runs.jsonl', None, 'Runs of the system against a task suite'),
    "eval_scorecard": ArtifactSpec('research-eval-harness', 'evals/scorecard.json', None, 'System-level scores'),
    "evaluator_code": ArtifactSpec('evaluator-builder', 'evaluation/evaluate.py', None, 'Scoring implementation (grader side)'),
    "evaluator_spec": ArtifactSpec('evaluator-builder', 'evaluation/evaluator_spec.md', None, 'Metric semantics and validity rules'),
    "evidence_graph": ArtifactSpec('claim-evidence-graph', 'evidence/evidence_graph.jsonl', 'ClaimEvidence', 'Claim -> evidence edges'),
    "experiment_ledger": ArtifactSpec('experiment-runner', 'experiment_ledger.jsonl', 'ExperimentResult', 'Append-only record of every run'),
    "experiment_specs": ArtifactSpec('research-blueprint-compiler', 'experiments/*.yaml', 'ExperimentSpec', 'Falsifiable experiment specifications'),
    "experiment_tree": ArtifactSpec('experiment-runner', 'experiments/experiment_tree.json', None, 'Search tree over experimental branches'),
    "failure_diagnosis": ArtifactSpec('codebase-scaffolder', 'experiments/failure_diagnosis.json', None, 'Root-cause classification of a failed run'),
    "fallback_decision_log": ArtifactSpec('reproduction-fallback-planner', 'reproduction/fallback_decisions.jsonl', None, 'Degradation decisions and their justification'),
    "feasibility_report": ArtifactSpec('idea-evaluator', 'ideas/feasibility_report.json', None, 'Feasibility and uncertainty, scored separately'),
    "figure_generation_trace": ArtifactSpec('figure-factory', 'figures/generation_trace.json', None, 'How each figure was produced'),
    "figure_plan": ArtifactSpec('manuscript-builder', 'paper/figure_plan.json', None, 'Which figures the argument requires'),
    "figure_table_index": ArtifactSpec('paper-model-builder', 'source/figure_table_index.json', None, 'Index of figures/tables with anchors'),
    "finding_memory_graph": ArtifactSpec('finding-memory', 'findings/memory_graph.json', None, 'Relations between findings'),
    "findings": ArtifactSpec('finding-memory', 'findings.jsonl', None, 'Distilled durable findings'),
    "gap_evidence": ArtifactSpec('idea-seed-miner', 'ideas/gap_evidence.md', None, 'Citations supporting each gap'),
    "gap_ledger": ArtifactSpec('idea-seed-miner', 'ideas/gap_ledger.jsonl', None, 'Evidenced research gaps'),
    "hidden_tests": ArtifactSpec('evaluator-builder', 'evaluation/hidden_tests/', None, 'Decisive tests, never mounted into agent context'),
    "idea_lineage_graph": ArtifactSpec('idea-portfolio-generator', 'ideas/lineage_graph.json', None, 'Parent-child lineage of ideas'),
    "idea_mode_constraints": ArtifactSpec('reproduction-fallback-planner', 'reproduction/idea_mode_constraints.json', None, 'Which innovation modes remain admissible at this RL'),
    "idea_pareto_front": ArtifactSpec('idea-ranker', 'ideas/pareto_front.json', None, 'Non-dominated set'),
    "idea_portfolio": ArtifactSpec('idea-portfolio-generator', 'ideas/idea_portfolio.json', 'IdeaCandidate', 'Candidate innovation directions'),
    "implementation_plan": ArtifactSpec('codebase-scaffolder', 'code/implementation_plan.md', None, 'Mapping from blueprint to modules'),
    "integrity_gate": ArtifactSpec('claim-citation-auditor', 'review/integrity_gate.json', None, 'Pre-submission integrity verdict'),
    "landscape_report": ArtifactSpec('literature-search', 'literature/landscape.md', None, 'Narrative landscape of the field'),
    "layout_warnings": ArtifactSpec('paper-ingest', 'source/layout_warnings.md', None, 'Parse/layout risks needing human check'),
    "library_hits": ArtifactSpec('literature-search', 'literature/library_hits.jsonl', None, "Matches in the user's personal library"),
    "library_note_links": ArtifactSpec('literature-search', 'literature/note_links.json', None, 'Links to user notes/annotations'),
    "literature_candidates": ArtifactSpec('literature-search', 'literature/literature_candidates.jsonl', None, 'Retrieved candidate works'),
    "literature_retrieval_log": ArtifactSpec('literature-search', 'literature/retrieval_log.jsonl', None, 'Provider calls, quotas, coverage gaps'),
    "literature_search_plan": ArtifactSpec('literature-search', 'literature/search_plan.json', None, 'Query families and coverage plan'),
    "locator_map": ArtifactSpec('paper-ingest', 'source/locator_map.json', None, 'Text span -> page/section anchors'),
    "manuscript_draft": ArtifactSpec('manuscript-builder', 'paper/main.tex|main.md', None, 'Evidence-bound manuscript draft'),
    "manuscript_pdf": ArtifactSpec('manuscript-builder', 'paper/main.pdf', None, 'Rendered manuscript (optional)'),
    "manuscript_spine": ArtifactSpec('manuscript-builder', 'paper/manuscript_spine.json', None, 'Central argument skeleton'),
    "meta_analysis": ArtifactSpec('integrity-auditor', 'analysis/meta_analysis.json', None, 'Aggregation across repeated trials'),
    "meta_analysis_decision": ArtifactSpec('integrity-auditor', 'analysis/decision.md', None, 'Keep/kill decision with rationale'),
    "method_dependency_graph": ArtifactSpec('paper-model-builder', 'evidence/dependency_graph.json', None, 'Dependencies between method components'),
    "mutant_candidates": ArtifactSpec('idea-portfolio-generator', 'ideas/mutant_candidates.jsonl', None, 'Mutated/recombined idea variants'),
    "negative_findings": ArtifactSpec('finding-memory', 'findings/negative_findings.jsonl', None, 'Curated negative and null results'),
    "normalized_text": ArtifactSpec('paper-ingest', 'source/normalized_text.md', None, 'Layout-normalized full text'),
    "novelty_report": ArtifactSpec('idea-evaluator', 'ideas/novelty_report.json', None, 'Novelty status with coverage limits'),
    "paper_assets": ArtifactSpec('paper-ingest', 'source/assets/', None, 'Extracted figures, tables, equations'),
    "paper_model": ArtifactSpec('paper-model-builder', 'source/paper_model.json', 'PaperModel', 'Structured model of the source paper'),
    "paper_source_file": ArtifactSpec('paper-ingest', 'source/paper.pdf|.html', None, 'Fetched primary source document'),
    "progress_state": ArtifactSpec('researchforge-orchestrator', '.researchforge/progress.json', None, 'Budget, stage and pace state'),
    "provenance_log": ArtifactSpec('experiment-runner', 'provenance.jsonl', None, 'Append-only artifact lineage'),
    "provider_registry": ArtifactSpec('literature-provider-manager', 'literature/provider_registry.json', None, 'Scholarly API providers, auth state, quota and rate limits'),
    "quest_repo": ArtifactSpec('project-repo-manager', '.researchforge/quest_repo.json', None, 'The research quest Git repository'),
    "quota_ledger": ArtifactSpec('literature-provider-manager', 'literature/quota_ledger.jsonl', None, 'Per-provider call/quota consumption over the run'),
    "ranked_branches": ArtifactSpec('experiment-runner', 'experiments/ranked_branches.json', None, 'Branches ranked by measured evidence'),
    "ranked_ideas": ArtifactSpec('idea-ranker', 'ideas/ranked_ideas.json', None, 'Multi-criteria ranked directions'),
    "ranking_rationale": ArtifactSpec('idea-ranker', 'ideas/ranking_rationale.md', None, 'Decisive tradeoffs and swing evidence'),
    "release_bundle": ArtifactSpec('release-gate', 'release/', None, 'Packaged final deliverables'),
    "release_manifest": ArtifactSpec('release-gate', 'release/release_manifest.json', None, 'What shipped and under what gates'),
    "release_report": ArtifactSpec('release-gate', 'release/release_report.md', None, 'Gate outcomes and open items'),
    "repair_commits": ArtifactSpec('codebase-scaffolder', 'code/.git/repair_commits', None, 'Bounded repair commits'),
    "repro_failure_taxonomy": ArtifactSpec('result-reproducer', 'reproduction/failure_taxonomy.jsonl', None, 'Classified reasons reproduction fell short of RL4'),
    "reproduction_report": ArtifactSpec('result-reproducer', 'baseline/reproduction_report.json', None, 'Reproduction attempt outcome'),
    "research_blueprint": ArtifactSpec('research-blueprint-compiler', 'research_blueprint.yaml', 'ResearchBlueprint', 'Executable plan for the selected direction'),
    "research_state": ArtifactSpec('researchforge-orchestrator', '.researchforge/research_state.json', None, 'Top-level state machine state'),
    "resolved_references": ArtifactSpec('citation-resolver', 'literature/references.jsonl', None, 'DOI/arXiv-resolved reference records'),
    "response_to_reviewers": ArtifactSpec('review-simulator', 'review/response_to_reviewers.md', None, 'Evidence-grounded response draft'),
    "retro_benchmark": ArtifactSpec('retrospective-benchmark-builder', 'evals/retro_benchmark.jsonl', None, 'Seed papers paired with their real published follow-up work'),
    "retro_benchmark_report": ArtifactSpec('retrospective-benchmark-builder', 'evals/retro_benchmark_report.md', None, 'Construction method, leakage controls and known limits'),
    "review_report": ArtifactSpec('review-simulator', 'review/review_report.json', None, 'Simulated reviewer assessment'),
    "review_triage": ArtifactSpec('review-simulator', 'review/review_triage.json', None, 'Atomic reviewer concerns, triaged'),
    "revision_experiment_plan": ArtifactSpec('review-simulator', 'review/experiment_plan.md', None, 'P0-P3 additional experiments'),
    "revision_matrix": ArtifactSpec('review-simulator', 'review/revision_matrix.csv', None, 'Concern x action x evidence'),
    "sandbox_container_config": ArtifactSpec('sandbox-provisioner', 'experiments/container.yaml', None, 'Container/venv definition'),
    "sandbox_manifest": ArtifactSpec('sandbox-provisioner', 'experiments/sandbox_manifest.json', None, 'Sandbox identity and limits'),
    "section_map": ArtifactSpec('paper-model-builder', 'source/section_map.json', None, 'Canonical section tree'),
    "selected_direction": ArtifactSpec('user-feedback-gate', 'ideas/selected_direction.json', None, 'Human-approved direction (or auto decision record)'),
    "selected_figure": ArtifactSpec('figure-factory', 'figures/selected/', None, 'Chosen figure per storyboard item'),
    "source_manifest": ArtifactSpec('paper-ingest', 'source/source_manifest.json', None, 'Retrieval provenance of the source'),
    "source_repro_metrics": ArtifactSpec('result-reproducer', 'reproduction/source_metrics.json', None, 'Locally measured numbers vs numbers reported in the source paper'),
    "source_repro_plan": ArtifactSpec('result-reproducer', 'reproduction/repro_plan.yaml', None, 'What of the SOURCE paper will be reproduced and at what scale'),
    "source_repro_report": ArtifactSpec('result-reproducer', 'reproduction/source_repro_report.json', 'ReproductionLevel', "Reproduction outcome of the SOURCE paper's own results, graded RL0-RL4"),
    "speaker_notes": ArtifactSpec('deck-factory', 'slides/speaker_notes.md', None, 'Speaker notes per slide'),
    "stats_audit": ArtifactSpec('integrity-auditor', 'analysis/stats_audit.json', None, 'Statistical validity findings'),
    "submission_blockers": ArtifactSpec('claim-citation-auditor', 'review/submission_blockers.md', None, 'Blocking issues before submission'),
    "svg_element_map": ArtifactSpec('figure-factory', 'figures/element_map.json', None, 'Semantic labels for SVG elements'),
    "svg_validation_report": ArtifactSpec('figure-factory', 'figures/validation_report.md', None, 'Editability/fidelity check'),
    "system_matrix": ArtifactSpec('literature-search', 'literature/system_matrix.csv', None, 'Comparable systems x capabilities'),
    "visual_notes": ArtifactSpec('paper-ingest', 'source/visual_notes.jsonl', None, 'Observations from rendered pages'),
    "weakness_map": ArtifactSpec('idea-seed-miner', 'ideas/weakness_map.json', None, 'Assumptions, failure modes, blind spots'),
}

@dataclass(frozen=True)
class SkillContract:
    consumes: tuple[str, ...]
    produces: tuple[str, ...]
    external: tuple[str, ...]
    feedback: tuple[str, ...]
    depends_on: tuple[str, ...]

SKILLS: Final[dict[str, SkillContract]] = {
    "citation-resolver": SkillContract(('provider_registry',), ('bibliography', 'citation_clusters', 'citation_gap_candidates', 'citation_graph', 'citation_resolution_report', 'resolved_references'), ('external: personal library metadata', 'external: raw reference strings or identifiers', 'external: seed paper canonical identifier'), (), ('literature-provider-manager',)),
    "claim-citation-auditor": SkillContract(('comparison_mode', 'draft_manifest', 'evidence_graph', 'experiment_ledger', 'experiment_specs', 'manuscript_draft', 'resolved_references', 'source_repro_report', 'stats_audit'), ('citation_audit', 'claim_audit', 'integrity_gate', 'submission_blockers'), (), ('response_to_reviewers', 'review_triage', 'revision_experiment_plan', 'revision_matrix'), ('citation-resolver', 'claim-evidence-graph', 'experiment-runner', 'integrity-auditor', 'manuscript-builder', 'reproduction-fallback-planner', 'research-blueprint-compiler', 'result-reproducer')),
    "claim-evidence-graph": SkillContract(('paper_model', 'resolved_references'), ('claim_registry', 'evidence_graph'), (), ('experiment_ledger', 'findings'), ('citation-resolver', 'paper-model-builder')),
    "codebase-scaffolder": SkillContract(('baseline_assets', 'experiment_specs', 'research_blueprint'), ('code_tests', 'code_worktree', 'debug_terminal_status', 'failure_diagnosis', 'implementation_plan', 'repair_commits'), (), ('experiment_ledger',), ('research-blueprint-compiler', 'result-reproducer')),
    "data-analyst": SkillContract(('best_candidate', 'experiment_ledger', 'experiment_specs', 'experiment_tree', 'ranked_branches'), ('analysis_code', 'analysis_plots', 'analysis_report', 'analysis_results'), ('external: analysis question', 'external: raw dataset'), (), ('experiment-runner', 'research-blueprint-compiler')),
    "deck-factory": SkillContract(('comparison_mode', 'draft_manifest', 'editable_svg', 'experiment_ledger', 'manuscript_draft', 'manuscript_spine', 'meta_analysis', 'selected_figure', 'svg_element_map', 'svg_validation_report'), ('deck_manifest', 'defense_deck', 'speaker_notes'), ('external: PPTX template', 'external: defense audience profile', 'external: target talk duration'), (), ('experiment-runner', 'figure-factory', 'integrity-auditor', 'manuscript-builder', 'reproduction-fallback-planner')),
    "evaluator-builder": SkillContract((), ('evaluator_code', 'evaluator_spec', 'hidden_tests'), ('external: known failure modes and gaming patterns', 'external: research objective', 'external: submission/answer schema'), (), ()),
    "experiment-runner": SkillContract(('acceptance_criteria', 'baseline_assets', 'blueprint_dag', 'code_tests', 'code_worktree', 'debug_terminal_status', 'environment_lock', 'evaluator_code', 'evaluator_spec', 'experiment_specs', 'failure_diagnosis', 'hidden_tests', 'idea_lineage_graph', 'implementation_plan', 'mutant_candidates', 'repair_commits', 'research_blueprint', 'sandbox_container_config', 'sandbox_manifest'), ('artifact_manifest', 'best_candidate', 'experiment_ledger', 'experiment_tree', 'provenance_log', 'ranked_branches'), ('external: artifact creation and edit events', 'external: runtime execution events'), (), ('codebase-scaffolder', 'evaluator-builder', 'idea-portfolio-generator', 'research-blueprint-compiler', 'result-reproducer', 'sandbox-provisioner')),
    "figure-factory": SkillContract(('analysis_plots', 'analysis_results', 'evidence_graph', 'figure_plan', 'manuscript_spine'), ('editable_svg', 'figure_generation_trace', 'selected_figure', 'svg_element_map', 'svg_validation_report'), ('external: figure style reference', 'external: raster figure or structured visual spec', 'external: source raster figure', 'external: target venue'), (), ('claim-evidence-graph', 'data-analyst', 'manuscript-builder')),
    "finding-memory": SkillContract(('analysis_code', 'analysis_report', 'assumption_tests', 'baseline_deviation_log', 'baseline_license_risk', 'baseline_metrics', 'baseline_repo_rankings', 'benchmark_matrix', 'branch_map', 'checkpoint_metadata', 'citation_gap_candidates', 'citation_resolution_report', 'claim_registry', 'closest_prior_work', 'contribution_atoms', 'decision_log', 'experiment_ledger', 'experiment_tree', 'fallback_decision_log', 'figure_table_index', 'gap_evidence', 'landscape_report', 'layout_warnings', 'library_hits', 'library_note_links', 'literature_retrieval_log', 'literature_search_plan', 'locator_map', 'meta_analysis', 'meta_analysis_decision', 'paper_assets', 'paper_source_file', 'quest_repo', 'quota_ledger', 'repro_failure_taxonomy', 'reproduction_report', 'section_map', 'source_manifest', 'source_repro_metrics', 'source_repro_plan', 'system_matrix', 'visual_notes'), ('boundary_conditions', 'finding_memory_graph', 'findings', 'negative_findings'), (), ('deck_manifest', 'figure_generation_trace', 'manuscript_pdf', 'response_to_reviewers', 'review_triage', 'revision_experiment_plan', 'revision_matrix', 'speaker_notes'), ('citation-resolver', 'claim-evidence-graph', 'data-analyst', 'experiment-runner', 'idea-evaluator', 'idea-seed-miner', 'integrity-auditor', 'literature-provider-manager', 'literature-search', 'paper-ingest', 'paper-model-builder', 'project-repo-manager', 'reproduction-fallback-planner', 'result-reproducer', 'user-feedback-gate')),
    "idea-evaluator": SkillContract(('baseline_assets', 'citation_graph', 'comparison_mode', 'coverage_report', 'idea_portfolio', 'provider_registry', 'source_repro_report'), ('closest_prior_work', 'feasibility_report', 'novelty_report'), ('external: resource envelope (compute, time, budget)',), (), ('citation-resolver', 'idea-portfolio-generator', 'literature-provider-manager', 'reproduction-fallback-planner', 'result-reproducer')),
    "idea-portfolio-generator": SkillContract(('analogy_candidates', 'comparison_mode', 'gap_ledger', 'idea_mode_constraints', 'source_repro_report', 'weakness_map'), ('idea_lineage_graph', 'idea_portfolio', 'mutant_candidates'), ('external: code exemplars for mutation', 'external: resource envelope (compute, time, budget)'), (), ('idea-seed-miner', 'reproduction-fallback-planner', 'result-reproducer')),
    "idea-ranker": SkillContract(('comparison_mode', 'coverage_report', 'feasibility_report', 'idea_portfolio', 'novelty_report'), ('idea_pareto_front', 'ranked_ideas', 'ranking_rationale'), ('external: user priorities and weightings',), (), ('idea-evaluator', 'idea-portfolio-generator', 'literature-provider-manager', 'reproduction-fallback-planner')),
    "idea-seed-miner": SkillContract(('citation_clusters', 'contribution_atoms', 'coverage_report', 'literature_candidates', 'method_dependency_graph', 'paper_model', 'source_repro_report'), ('analogy_candidates', 'assumption_tests', 'gap_evidence', 'gap_ledger', 'weakness_map'), ('external: target venue', 'external: tool and domain catalog source'), (), ('citation-resolver', 'literature-provider-manager', 'literature-search', 'paper-model-builder', 'result-reproducer')),
    "integrity-auditor": SkillContract(('analysis_code', 'analysis_results', 'experiment_ledger', 'experiment_specs'), ('meta_analysis', 'meta_analysis_decision', 'stats_audit'), ('external: keep/kill decision criteria',), (), ('data-analyst', 'experiment-runner', 'research-blueprint-compiler')),
    "literature-provider-manager": SkillContract((), ('coverage_report', 'provider_registry', 'quota_ledger'), ('external: domain and recency scope', 'external: provider credentials and contact email for polite pools', 'external: run-level quota and cost budget'), (), ()),
    "literature-search": SkillContract(('coverage_report', 'paper_model', 'provider_registry'), ('benchmark_matrix', 'landscape_report', 'library_hits', 'library_note_links', 'literature_candidates', 'literature_retrieval_log', 'literature_search_plan', 'system_matrix'), ('external: landscape topic', 'external: library query', 'external: literature search objective', 'external: paper context for library lookup', 'external: personal library connector configuration', 'external: recency and time constraints', 'external: tool and domain catalog source'), (), ('literature-provider-manager', 'paper-model-builder')),
    "manuscript-builder": SkillContract(('bibliography', 'boundary_conditions', 'comparison_mode', 'evidence_graph', 'findings', 'meta_analysis', 'negative_findings', 'selected_direction'), ('draft_manifest', 'figure_plan', 'manuscript_draft', 'manuscript_pdf', 'manuscript_spine'), ('external: target venue', 'external: target venue template (LaTeX/Word style)'), ('selected_figure',), ('citation-resolver', 'claim-evidence-graph', 'finding-memory', 'integrity-auditor', 'reproduction-fallback-planner', 'user-feedback-gate')),
    "paper-ingest": SkillContract((), ('layout_warnings', 'locator_map', 'normalized_text', 'paper_assets', 'paper_source_file', 'source_manifest', 'visual_notes'), ('external: paper locator (URL/PDF/HTML/DOI/arXiv/local path)', 'external: rendered page images', 'external: supplementary URLs or files'), (), ()),
    "paper-model-builder": SkillContract(('locator_map', 'normalized_text'), ('contribution_atoms', 'figure_table_index', 'method_dependency_graph', 'paper_model', 'section_map'), (), (), ('paper-ingest',)),
    "project-repo-manager": SkillContract((), ('branch_map', 'checkpoint_metadata', 'quest_repo'), ('external: paper locator (URL/PDF/HTML/DOI/arXiv/local path)', 'external: project intent statement', 'external: workspace and retention policy'), (), ()),
    "release-gate": SkillContract(('artifact_manifest', 'bibliography', 'citation_audit', 'claim_audit', 'comparison_mode', 'defense_deck', 'finding_memory_graph', 'findings', 'integrity_gate', 'manuscript_draft', 'provenance_log', 'review_report', 'source_repro_report', 'stats_audit', 'submission_blockers'), ('release_bundle', 'release_manifest', 'release_report'), (), ('progress_state',), ('citation-resolver', 'claim-citation-auditor', 'deck-factory', 'experiment-runner', 'finding-memory', 'integrity-auditor', 'manuscript-builder', 'reproduction-fallback-planner', 'result-reproducer', 'review-simulator')),
    "reproduction-fallback-planner": SkillContract(('baseline_license_risk', 'repro_failure_taxonomy', 'source_repro_metrics', 'source_repro_report'), ('comparison_mode', 'fallback_decision_log', 'idea_mode_constraints'), ('external: resource envelope', 'external: user risk tolerance and target venue'), (), ('result-reproducer',)),
    "research-blueprint-compiler": SkillContract(('baseline_assets', 'comparison_mode', 'selected_direction', 'source_repro_report'), ('acceptance_criteria', 'blueprint_dag', 'experiment_specs', 'research_blueprint'), ('external: candidate method description', 'external: hypothesis under test', 'external: resource envelope (compute, time, budget)'), (), ('reproduction-fallback-planner', 'result-reproducer', 'user-feedback-gate')),
    "research-eval-harness": SkillContract(('evaluator_code', 'retro_benchmark', 'retro_benchmark_report'), ('eval_failure_taxonomy', 'eval_runs', 'eval_scorecard'), ('external: evaluation task suite', 'external: skill version under evaluation'), (), ('evaluator-builder', 'retrospective-benchmark-builder')),
    "researchforge-orchestrator": SkillContract(('comparison_mode', 'evidence_graph', 'idea_portfolio', 'paper_model', 'ranked_ideas', 'release_bundle', 'release_manifest', 'release_report', 'research_blueprint', 'selected_direction'), ('progress_state', 'research_state'), ('external: budget and cost policy', 'external: live runtime state feed', 'external: paper locator (URL/PDF/HTML/DOI/arXiv/local path)', 'external: resource envelope (compute, time, budget)', 'external: run mode (guided|auto|analysis-only)', 'external: user feedback on ranked ideas'), (), ('claim-evidence-graph', 'idea-portfolio-generator', 'idea-ranker', 'paper-model-builder', 'release-gate', 'reproduction-fallback-planner', 'research-blueprint-compiler', 'user-feedback-gate')),
    "result-reproducer": SkillContract(('benchmark_matrix', 'contribution_atoms', 'literature_candidates', 'paper_model', 'sandbox_manifest'), ('baseline_assets', 'baseline_deviation_log', 'baseline_license_risk', 'baseline_metrics', 'baseline_repo_rankings', 'repro_failure_taxonomy', 'reproduction_report', 'source_repro_metrics', 'source_repro_plan', 'source_repro_report'), ('external: preferred research direction hint', 'external: reproduction tolerance policy', 'external: resource envelope (compute, time, budget)', 'external: resource envelope (wall-clock cap, compute class, cost cap)', "external: sota_methods — current strongest methods on this paper's benchmarks"), ('comparison_mode',), ('literature-search', 'paper-model-builder', 'sandbox-provisioner')),
    "retrospective-benchmark-builder": SkillContract(('citation_graph', 'coverage_report', 'provider_registry'), ('retro_benchmark', 'retro_benchmark_report'), ('external: domain scope and venue list', 'external: seed time window and evaluation window'), (), ('citation-resolver', 'literature-provider-manager')),
    "review-simulator": SkillContract(('citation_audit', 'evidence_graph', 'experiment_ledger', 'integrity_gate', 'manuscript_draft', 'manuscript_spine'), ('response_to_reviewers', 'review_report', 'review_triage', 'revision_experiment_plan', 'revision_matrix'), ('external: resource envelope (compute, time, budget)', 'external: target venue'), (), ('claim-citation-auditor', 'claim-evidence-graph', 'experiment-runner', 'manuscript-builder')),
    "sandbox-provisioner": SkillContract((), ('environment_lock', 'sandbox_container_config', 'sandbox_manifest'), ('external: sandbox security profile',), (), ()),
    "skill-evolution-manager": SkillContract(('eval_failure_taxonomy', 'eval_runs', 'eval_scorecard'), (), ('external: held-out evaluation suite', 'external: skill catalog source', 'external: skill version under evaluation', 'external: skills directory path'), (), ('research-eval-harness',)),
    "user-feedback-gate": SkillContract(('comparison_mode', 'idea_pareto_front', 'ranked_ideas', 'ranking_rationale'), ('decision_log', 'selected_direction'), ('external: user feedback on ranked ideas',), (), ('idea-ranker', 'reproduction-fallback-planner')),
}

STATES: Final[tuple[str, ...]] = ('INGESTED', 'MODELED', 'EVIDENCE_EXPANDED', 'SOURCE_REPRO_ATTEMPTED', 'REPRO_LEVEL_ESTABLISHED', 'IDEAS_READY', 'HUMAN_SELECTION_REQUIRED', 'DIRECTION_SELECTED', 'BLUEPRINT_READY', 'BASELINE_ESTABLISHED', 'EXPERIMENTING', 'EVIDENCE_LOCKED', 'WRITING', 'REVIEWING', 'DEFENSE_READY', 'RELEASED')

BUILD_ORDER: Final[tuple[str, ...]] = ('literature-provider-manager', 'citation-resolver', 'paper-ingest', 'paper-model-builder', 'claim-evidence-graph', 'literature-search', 'sandbox-provisioner', 'result-reproducer', 'reproduction-fallback-planner', 'idea-seed-miner', 'idea-portfolio-generator', 'idea-evaluator', 'idea-ranker', 'user-feedback-gate', 'research-blueprint-compiler', 'codebase-scaffolder', 'evaluator-builder', 'experiment-runner', 'data-analyst', 'integrity-auditor', 'project-repo-manager', 'finding-memory', 'manuscript-builder', 'claim-citation-auditor', 'figure-factory', 'deck-factory', 'review-simulator', 'release-gate', 'retrospective-benchmark-builder', 'research-eval-harness', 'researchforge-orchestrator', 'skill-evolution-manager')

#: artifact -> spec, for artifacts that never cross a skill boundary.
#: They are still written to disk and still carry provenance; they are simply
#: not part of the public contract, so no other skill may depend on them.
INTERNAL_ARTIFACT_SPECS: Final[dict[str, dict[str, ArtifactSpec]]] = {
    "data-analyst": {
        "data_profile": ArtifactSpec("data-analyst", 'analysis/data_profile.json', None, 'Schema, distribution and quality profile'),
        "data_transform_log": ArtifactSpec("data-analyst", 'analysis/transform_log.jsonl', None, 'Every transformation applied'),
        "prepared_data": ArtifactSpec("data-analyst", 'analysis/prepared/', None, 'Cleaned, split, leakage-checked data'),
    },
    "deck-factory": {
        "deck_spec": ArtifactSpec("deck-factory", 'slides/deck_spec.json', None, 'Structured per-slide specification'),
        "slide_evidence": ArtifactSpec("deck-factory", 'slides/slide_evidence.json', None, 'Slide element -> project artifact links'),
        "slide_outline": ArtifactSpec("deck-factory", 'slides/slide_outline.md', None, 'Defense narrative outline'),
        "speaker_timing": ArtifactSpec("deck-factory", 'slides/speaker_timing.csv', None, 'Time budget per slide'),
    },
    "experiment-runner": {
        "run_index": ArtifactSpec("experiment-runner", 'run_index.sqlite', None, 'Queryable index over the ledger'),
    },
    "figure-factory": {
        "figure_candidates": ArtifactSpec("figure-factory", 'figures/candidates/', None, 'Generated figure variants'),
        "figure_captions": ArtifactSpec("figure-factory", 'figures/captions_draft.md', None, 'Draft captions tied to claims'),
        "figure_storyboard": ArtifactSpec("figure-factory", 'figures/figure_storyboard.json', None, 'Message and form for each figure'),
        "reconstructed_svg": ArtifactSpec("figure-factory", 'figures/reconstructed/', None, 'Vector reconstruction of a raster figure'),
        "svg_reconstruction_map": ArtifactSpec("figure-factory", 'figures/reconstruction_map.json', None, 'Source region -> vector element mapping'),
    },
    "idea-evaluator": {
        "resource_plan": ArtifactSpec("idea-evaluator", 'ideas/resource_plan.yaml', None, 'Compute/data/time plan per idea'),
    },
    "integrity-auditor": {
        "stats_required_fixes": ArtifactSpec("integrity-auditor", 'analysis/required_fixes.md', None, 'BLOCKER/HIGH items to resolve'),
    },
    "manuscript-builder": {
        "section_blueprint": ArtifactSpec("manuscript-builder", 'paper/section_blueprint.md', None, 'Per-section argumentative role'),
    },
    "research-blueprint-compiler": {
        "ablation_plan": ArtifactSpec("research-blueprint-compiler", 'experiments/ablation_plan.yaml', None, 'Ablations and counterfactual controls'),
    },
    "researchforge-orchestrator": {
        "progress_alerts": ArtifactSpec("researchforge-orchestrator", '.researchforge/alerts.jsonl', None, 'Budget/stall alerts'),
        "resume_token": ArtifactSpec("researchforge-orchestrator", '.researchforge/resume_token.json', None, 'Idempotent restart pointer'),
    },
    "result-reproducer": {
        "source_repro_env": ArtifactSpec("result-reproducer", 'reproduction/environment.lock', None, 'Exact environment in which reproduction was attempted'),
    },
    "review-simulator": {
        "revision_backlog": ArtifactSpec("review-simulator", 'review/revision_backlog.md', None, 'Prioritized revision items'),
    },
    "skill-evolution-manager": {
        "skill_audit_machine_report": ArtifactSpec("skill-evolution-manager", 'evals/machine_report.json', None, 'Machine-readable package audit'),
        "skill_audit_report": ArtifactSpec("skill-evolution-manager", 'evals/skill_audit_report.md', None, 'Human-readable package audit'),
        "skill_eval_comparison": ArtifactSpec("skill-evolution-manager", 'evals/skill_eval_comparison.json', None, 'Held-out comparison of skill versions'),
        "skill_patch": ArtifactSpec("skill-evolution-manager", 'evals/skill_patch.diff', None, 'Proposed bounded skill edit'),
        "skill_promotion_decision": ArtifactSpec("skill-evolution-manager", 'evals/promotion_decision.json', None, 'Promote/reject with rollback pointer'),
    },
}

INTERNAL_ARTIFACTS: Final[dict[str, tuple[str, ...]]] = {k: tuple(v) for k, v in INTERNAL_ARTIFACT_SPECS.items()}

CONTRACT_DIGEST: Final[str] = "b756e68c41a6a7a4"
